export const items = [
  { id: 1, name: 'The Legend of Zelda: Breath of the Wild', category: 'adventure',
    price: 59.99, tags: ['open-world', 'nintendo'],
    studio: { name: 'Nintendo EPD', country: 'JP' } },
  { id: 2, name: 'God of War', category: 'action',
    price: 39.99, tags: ['mythology', 'playstation'],
    studio: { name: 'Santa Monica Studio', country: 'US' } },
  { id: 3, name: 'Hades', category: 'roguelike',
    price: 24.99, tags: ['indie', 'greek-mythology'],
    studio: { name: 'Supergiant Games', country: 'US' } },
  { id: 4, name: 'Stardew Valley', category: 'simulation',
    price: 13.99, tags: ['indie', 'farming', 'relaxing'],
    studio: { name: 'ConcernedApe', country: 'US' } },
  { id: 5, name: 'Dark Souls III', category: 'action',
    price: 29.99, tags: ['souls-like', 'difficult'],
    studio: { name: 'FromSoftware', country: 'JP' } },
  { id: 6, name: 'Celeste', category: 'platformer',
    price: 19.99, tags: ['indie', 'difficult', 'pixel-art'],
    studio: { name: 'Maddy Makes Games', country: 'CA' } },
  { id: 7, name: 'Minecraft', category: 'sandbox',
    price: 26.95, tags: ['building', 'survival', 'multiplayer'],
    studio: { name: 'Mojang', country: 'SE' } },
  { id: 8, name: 'Hollow Knight', category: 'platformer',
    price: 14.99, tags: ['indie', 'metroidvania'],
    studio: { name: 'Team Cherry', country: 'AU' } },
]